languageCode = "en"
languageName = "English"
weight = 1
title = "DIADZ"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/diadzc.png"
  # secondaryLogo = "img/DIADZ.png"
  description = "Headquarters"
  copyright = ""

[author]
  name = "Die Irren aus der Zukunft"
  image = "/img/diadzc.png"
  headline = "Est. 2017"
  bio = "未来は私たちのものです"
  links = [
    { codeberg = "https://codeberg.org/DIADZ" },
    { github = "https://github.com/Die-Irrenanstalt" }
  ]
