# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Mitglieder"
  pageRef = "/members"
  weight = 10

[[main]]
  name = "Spenden"
  pageRef = "/donate"
  weight = 20

[[main]]
  name = "Dienste"
  pageRef = "/services"
  weight = 30

[[main]]
  name = "Designs"
  pageRef = "/themes"
  weight = 40

[[main]]
  name = "Gallerie"
  url = "https://bilder.diadz.de/"
  weight = 50

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Über"
  pageRef = "/about"
  weight = 10

[[footer]]
  name = "Status"
  url = "https://diadz.instatus.com/"
  weight = 20

[[footer]]
  name = "Kontakt"
  pageRef = "/contact"
  weight = 40

[[footer]]
  name = "Datenschutz"
  pageRef = "/privacy"
  weight = 50