[hugoVersion]
  extended = false
  min = "0.87.0"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/icons/font-awesome"
